name: Godot CI to itch.io

on:
  push:     
    branches: [ main ]

env:
  EXPORT_NAME: Amusnet-Hackaton
  GODOT_VERSION: 4.5.1

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.5.1
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Updated to v4
        with:     
          lfs: true
      
      - name: Setup Export Templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      
      - name: Web Build
        run: |           
          mkdir -p builds/web
          godot --headless --export-release "HTML5" ./builds/web/index.html
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: web-build
          path: builds/web
      
      - name: Publish to itch.io
        uses: manleydev/butler-publish-itchio-action@master
        with:  # Use 'with' instead of 'env' for this action
          butler_credentials: ${{ secrets.ITCHIO_TOKEN }}
          itch_user: vikbro
          itch_game: amusnet-hackaton
          channel: web
          directory: builds/web