name: Publish to Itch.io

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Godot Export
        id: export
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2/Godot_v4.2-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2/Godot_v4.2-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
          # Use the GitHub Actions workflow cache to cache the Godot export templates and Godot executable. 
          # Helps speed up builds by not having to download them every time.
          cache: true
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}

      - name: Publish to Itch
        uses: Ayowel/butler-to-itch@v1.0.0
        with:
          butler_key: ${{secrets.ITCHIO_TOKEN}}
          itch_user: struhy-xd
          itch_game: painted-mosaics
          version: ${{ github.ref_name }}
          files: "${{ steps.export.outputs.archive_directory }}/mosaics-web.zip"
